name: Docker Hub Deployment

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version
      id: versioning
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./cwsoffline/cwsstore
        file: ./cwsoffline/cwsstore/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/cwsstore:latest
          ${{ secrets.DOCKER_USERNAME }}/cwsstore:${{ steps.versioning.outputs.build_number }}
