name: docker-cicd

on:
  push:
    branches:
      - 'main'
  release:
    types: [edited, released]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
          
      - name: Build and push cwssync
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cwsoffline/cwssync/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cwssync:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cwssync:${{ steps.get_version.outputs.version-without-v }}
  
      - name: Build and push cwsbuild
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cwsoffline/cwsbuild/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cwsbuild:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cwsbuild:${{ steps.get_version.outputs.version-without-v }}
  
      - name: Build and push cwsstore
        uses: docker/build-push-action@v6
        with:
          context: ./cwsoffline/cwsstore
          file: ./cwsoffline/cwsstore/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cwsstore:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cwsstore:${{ steps.get_version.outputs.version-without-v }}
  